language: python

python:
  - "3.8"

before_install:
  - choco install python --version 3.8.0
  - python -m pip install --upgrade pip

env: PATH=/c/Python38:/c/Python38/Scripts:$PATH

install:
  - pip install -r requirements.txt

notifications:
  email: false

script:
  - pytest
